### ISSUE TITLE
gethostbyname

### ISSUE THREAD

**Issue by yfang1644** [Shaloc/Cluster-computing#2]
1. remove nameserver from /etc/resolv.conf. ( therefore can't access network by name)
2. keep /etc/resolv.conf working, add /etc/nsswitch.conf:
   hosts:  files dns

**Comment by Shaloc** [comment]
It's simply beacuse the hostname is not in hosts, just add
```bash
xxx.xxx.xxx.xxx hostname
```
to `/etc/hosts` can solve this problem.
